// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Simple greeting command for demonstration purposes.
 */
async greet(name: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("greet", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads user preferences from disk.
 * Returns default preferences if the file doesn't exist.
 */
async loadPreferences() : Promise<Result<AppPreferences, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_preferences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves user preferences to disk.
 * Uses atomic write (temp file + rename) to prevent corruption.
 */
async savePreferences(preferences: AppPreferences) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_preferences", { preferences }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sends a native system notification.
 * On mobile platforms, returns an error as notifications are not yet supported.
 */
async sendNativeNotification(title: string, body: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_native_notification", { title, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves emergency data to a JSON file for later recovery.
 * Validates filename and enforces a 10MB size limit.
 */
async saveEmergencyData(filename: string, data: JsonValue) : Promise<Result<null, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_emergency_data", { filename, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads emergency data from a previously saved JSON file.
 * Returns FileNotFound if the file doesn't exist.
 */
async loadEmergencyData(filename: string) : Promise<Result<JsonValue, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_emergency_data", { filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes recovery files older than 7 days.
 * Returns the count of removed files.
 */
async cleanupOldRecoveryFiles() : Promise<Result<number, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_old_recovery_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Shows the quick pane window and makes it the key window (for keyboard input).
 */
async showQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dismisses the quick pane window.
 * On macOS, resigns key window status before hiding to avoid activating main window.
 */
async dismissQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dismiss_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggles the quick pane window visibility.
 */
async toggleQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the default shortcut constant for frontend use.
 */
async getDefaultQuickPaneShortcut() : Promise<string> {
    return await TAURI_INVOKE("get_default_quick_pane_shortcut");
},
/**
 * Updates the global shortcut for the quick pane.
 * Pass None to reset to default.
 */
async updateQuickPaneShortcut(shortcut: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_quick_pane_shortcut", { shortcut }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run `npx <args>` with the resolved Node runtime on the child's `PATH`.
 * Returns the exit code and output; a non-zero exit is the caller's to interpret.
 */
async runSkillsCli(args: string[], cwd: string | null) : Promise<Result<SkillsCliOutput, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_skills_cli", { args, cwd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetches the skills leaderboard (default: all-time, page 0, up to 500).
 */
async fetchSkillsLeaderboard(view: string | null, page: number | null, perPage: number | null) : Promise<Result<SkillsShSkill[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_skills_leaderboard", { view, page, perPage }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Searches skills by name/description (min 2 characters on the API).
 */
async searchSkills(q: string, limit: number | null) : Promise<Result<SkillsShSkill[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_skills", { q, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetches enrichment and related skills for a catalog skill.
 */
async fetchSkillDetail(skillId: string) : Promise<Result<SkillDetailData, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_skill_detail", { skillId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetches cached or on-demand security audits for a catalog skill.
 */
async fetchSkillAudits(skillId: string) : Promise<Result<SkillAuditsData, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_skill_audits", { skillId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scan global provider + Universal skill directories into one normalized snapshot.
 * Served from cache while a stat-only fingerprint of those directories is
 * unchanged, so the Installed tab's rescan-per-activation is not a full walk.
 */
async scanInstalledSkills() : Promise<Result<InstalledScanSnapshot, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_installed_skills") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Enumerate project directories at depth one or two below an explicitly selected root.
 */
async listProjects(root: string) : Promise<Result<ProjectInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_projects", { root }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scan project-local Universal and provider skill folders.
 */
async scanProjectSkills(projectPath: string) : Promise<Result<InstalledScanSnapshot, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_project_skills", { projectPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reveal a provider (or `universal`) skills directory in Finder/Explorer.
 * Returns `false` when the directory is missing. Does not rescan skills.
 */
async revealProviderSkillsDir(providerId: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reveal_provider_skills_dir", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reveal an arbitrary filesystem path in Finder/Explorer.
 * Returns `false` when the path is missing. Does not rescan skills.
 */
async revealPath(path: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reveal_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete one skill folder from the Universal `~/.agents/skills` cache.
 * Returns `false` when the folder is already missing.
 */
async deleteUniversalSkill(uninstallName: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_universal_skill", { uninstallName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Copy one installed skill into selected provider folders as directory symlinks.
 * Returns independent per-provider outcomes so partial success is preserved.
 */
async copySkillToProviders(uninstallName: string, providerIds: string[]) : Promise<Result<CopySkillToProvidersResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copy_skill_to_providers", { uninstallName, providerIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Install one skill from `source` into Universal and the given providers.
 * Spawns no subprocess; a source already in the cache installs without network.
 * `project_path` selects project scope, `null` installs into the home roots.
 */
async installSkill(source: string, skillName: string, providerIds: string[], projectPath: string | null) : Promise<Result<SkillProjectionResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_skill", { source, skillName, providerIds, projectPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove one skill from each given target, `universal` included when the
 * caller lists it. Outcomes are independent: a failing target never stops the
 * rest, so the Universal cleanup always runs.
 */
async uninstallSkill(uninstallName: string, providerIds: string[]) : Promise<Result<SkillProjectionResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("uninstall_skill", { uninstallName, providerIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Application preferences that persist to disk.
 * Only contains settings that should be saved between sessions.
 */
export type AppPreferences = { theme: string; 
/**
 * Global shortcut for quick pane (e.g., "CommandOrControl+Shift+.")
 * If None, uses the default shortcut
 */
quick_pane_shortcut: string | null; 
/**
 * User's preferred language (e.g., "en", "es", "de")
 * If None, uses system locale detection
 */
language: string | null }
export type CopyProviderResult = { providerId: string; status: CopyProviderStatus; message?: string | null }
export type CopyProviderStatus = "copied" | "conflict" | 
/**
 * The destination is inside the read-only Claude plugin cache.
 */
"refused" | "failed"
export type CopySkillToProvidersResult = { results: CopyProviderResult[] }
export type InstalledScanSnapshot = { scannedAt: string; source: ProviderRegistrySourceMeta; universal: UniversalScanInfo; providers: ScannedProvider[]; skills: ScannedSkill[]; warnings: ScanWarning[] }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type ProjectInfo = { name: string; path: string; depth: number; skillCount: number }
export type ProviderRegistrySourceMeta = { repositoryUrl: string; commit: string; license: string; attribution: string }
/**
 * Error types for recovery operations (typed for frontend matching)
 */
export type RecoveryError = 
/**
 * File does not exist (expected case, not a failure)
 */
{ type: "FileNotFound" } | 
/**
 * Filename validation failed
 */
{ type: "ValidationError"; message: string } | 
/**
 * Data exceeds size limit
 */
{ type: "DataTooLarge"; max_bytes: number } | 
/**
 * File system read/write error
 */
{ type: "IoError"; message: string } | 
/**
 * JSON serialization/deserialization error
 */
{ type: "ParseError"; message: string }
export type RelatedSkill = { skillId: string; score: number; repository: string | null; source: string | null; sourceUrl: string | null; installCount: number | null }
export type ScanWarning = { code: ScanWarningCode; message: string; providerId?: string | null; path?: string | null }
export type ScanWarningCode = "provider_empty" | "skills_dir_missing" | "entry_skipped" | "universal_empty"
export type ScannedProvider = { id: string; name: string; universal: boolean; detected: boolean; skillsDir: string | null; skillsDirExists: boolean; skillCount: number }
export type ScannedSkill = { name: string; uninstallName: string; description: string; scope: string; providerIds: string[]; origins: SkillOrigin[]; paths: ScannedSkillPath[] }
export type ScannedSkillPath = { path: string; originalPath?: string | null }
export type SkillAuditEntry = { provider: string; slug: string; status: string; summary: string; auditedAt: string; riskLevel?: string | null; categories?: string[] | null }
export type SkillAuditsData = { skillId: string; audits: SkillAuditsPayload | null; source: string; auditsFetchedAt: string | null }
export type SkillAuditsPayload = { id: string; source: string; slug: string; audits: SkillAuditEntry[] }
export type SkillDetailData = { skillId: string; pageSnapshot?: SkillPageSnapshot | null; pageScrapedAt?: string | null; repository?: string | null; source?: string | null; installCount?: number | null; sourceUrl?: string | null; installSeries?: number[]; enrichment: SkillEnrichment | null; related: RelatedSkill[] }
export type SkillEnrichment = { skillId: string; contentHash: string; required: SkillEnrichmentRequired; optional: JsonValue; estimatedReadTimeMinutes: number }
export type SkillEnrichmentRequired = { primaryGoal: string; requires: string[]; estimatedComplexity: string; bestFor: string[] }
/**
 * Where a scanned skill came from. A skill can have several origins at once —
 * the same skill may sit in `~/.agents/skills` and also ship inside a plugin.
 */
export type SkillOrigin = 
/**
 * Found directly in a provider (or Universal / project) skills directory.
 */
{ kind: "providerDirectory"; providerId: string } | 
/**
 * Delivered by a Claude Code plugin.
 */
{ kind: "claudePlugin"; plugin: string; marketplace: string; version: string }
export type SkillPageSnapshot = { summary?: string | null; topics?: string[] | null; repository?: string | null; source?: string | null; stars?: number | null; firstSeen?: string | null; installCommand?: string | null; related?: JsonValue | null; weeklyInstalls?: number[] | null; skillMdPreview?: string | null }
export type SkillProjectionResult = { results: SkillTargetResult[]; 
/**
 * Answered from the acquisition cache, with no network request. Always
 * false for an uninstall.
 */
cacheHit: boolean }
export type SkillTargetResult = { providerId: string; status: SkillTargetStatus; message?: string | null }
export type SkillTargetStatus = 
/**
 * Linked or copied in.
 */
"written" | 
/**
 * Already correct — including a provider that shares the Universal root.
 */
"already_present" | 
/**
 * Something we will not delete is in the way.
 */
"conflict" | "removed" | "absent" | 
/**
 * The destination is inside the read-only Claude plugin cache.
 */
"refused" | "failed"
export type SkillsCliOutput = { code: number; stdout: string; stderr: string }
export type SkillsShSkill = { id: string; slug: string; name: string; source: string; installs: number; sourceType: string; installUrl?: string | null; url: string; isDuplicate?: boolean | null }
export type UniversalScanInfo = { skillsDir: string; skillsDirExists: boolean; skillCount: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
