import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { assertSeedSize } from './seed-utils.mjs'

const DEFAULT_COUNT = 12
const outputPath = resolve('src/data/skills-seed.ts')

function argValue(name) {
  const index = process.argv.indexOf(name)
  return index === -1 ? undefined : process.argv[index + 1]
}

async function loadSnapshot() {
  const inputPath = argValue('--input') ?? process.env.SEED_INPUT_FILE
  if (inputPath) return JSON.parse(await readFile(resolve(inputPath), 'utf8'))

  const sourceUrl =
    process.env.SEED_SOURCE_URL ??
    `${process.env.SKILLS_PROXY_BASE_URL ?? 'http://localhost:3000'}/api/skills/seed`
  const response = await fetch(sourceUrl, {
    headers: { Accept: 'application/json' },
  })
  if (!response.ok) throw new Error(`Seed source failed: ${response.status}`)
  return response.json()
}

function normalizeSkill(skill) {
  return {
    id: String(skill.id),
    slug: String(skill.slug),
    name: String(skill.name ?? skill.slug),
    source: String(skill.source),
    installs: Number(skill.installs ?? 0),
    sourceType: String(skill.sourceType ?? 'github'),
    ...(skill.installUrl ? { installUrl: String(skill.installUrl) } : {}),
    url: String(skill.url ?? `https://skills.sh/${skill.id}`),
  }
}

function normalizeSnapshot(snapshot) {
  const skills = Array.isArray(snapshot) ? snapshot : snapshot.skills
  if (!Array.isArray(skills))
    throw new Error('Seed snapshot must contain skills')
  const details = Array.isArray(snapshot) ? [] : (snapshot.details ?? [])
  return {
    skills: skills
      .slice(0, Number(argValue('--count') ?? DEFAULT_COUNT))
      .map(normalizeSkill),
    details: Object.fromEntries(
      details
        .filter(detail => detail?.enrichment)
        .map(detail => [detail.skillId, detail])
    ),
  }
}

const seed = normalizeSnapshot(await loadSnapshot())
const output = `import type { SkillDetailData, SkillsShSkill } from '@/catalog/types'\n\n/** Generated by scripts/generate-seed.mjs. Do not edit by hand. */\nexport const skillsSeed: SkillsShSkill[] = ${JSON.stringify(seed.skills, null, 2)}\n\nexport const skillsSeedDetails: Record<string, SkillDetailData> = ${JSON.stringify(seed.details, null, 2)}\n\nexport function getSeedForView(_view: string): SkillsShSkill[] {\n  return skillsSeed\n}\n\nexport function getSeedDetail(skillId: string): SkillDetailData | undefined {\n  return skillsSeedDetails[skillId]\n}\n`
assertSeedSize(Buffer.byteLength(output), outputPath)
await writeFile(outputPath, output)
console.log(
  `Generated ${seed.skills.length} skills and ${Object.keys(seed.details).length} enriched details`
)
